# Generated by Django 5.1.3 on 2025-12-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="voice_note",
            field=models.FileField(blank=True, null=True, upload_to="voice_notes/"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="talk_id",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
