# Generated by Django 6.0 on 2025-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_email_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
    ]
