# Generated by Django 6.0 on 2025-12-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='couple',
            field=models.CharField(default='copule', max_length=100),
            preserve_default=False,
        ),
    ]
