# Generated by Django 5.1.3 on 2025-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(default="exit"),
            preserve_default=False,
        ),
    ]
