# Generated by Django 5.1.3 on 2025-12-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
