# Generated by Django 5.1.3 on 2025-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_story_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="ban_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
