# Generated by Django 5.1.3 on 2025-12-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_profile_ban_reason_profile_ban_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
