# Generated by Django 5.1.3 on 2025-12-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_profile_is_verified_profile_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("developer", "Developer"),
                    ("app_inspector", "App Inspector"),
                    ("creator", "Creator"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
