# Generated by Django 5.1.3 on 2025-12-30 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="myapp.message",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
    ]
