# Generated by Django 5.1.3 on 2025-12-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_message_parent_message_profile_is_typing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="Official Message",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
