# Generated by Django 5.1.3 on 2026-01-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="parent_message",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("developer", "Developer"),
                    ("app_inspector", "App Inspector"),
                    ("creator", "Creator"),
                    ("Official", "Official"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
