# Generated by Django 5.1.3 on 2026-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_rename_parent_message_message_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="talk_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stories/"),
        ),
    ]
