# Generated by Django 5.1.3 on 2026-01-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_profile_talk_id_alter_story_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Stories"},
        ),
    ]
