# Generated by Django 5.1.3 on 2026-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_story_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="talk_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
